//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerAccounts
    {
        public int id { get; set; }
        public Nullable<int> applicationId { get; set; }
        public string accountNumber { get; set; }
        public string accountPassword { get; set; }
        public string telephoneNumber { get; set; }
        public string serviceAvailed { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual userApplications userApplications { get; set; }
    }
}
