//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificationLogs
    {
        public int logId { get; set; }
        public string actionType { get; set; }
        public Nullable<int> applicationId { get; set; }
        public Nullable<System.DateTime> actionDate { get; set; }
    
        public virtual userApplications userApplications { get; set; }
    }
}
