//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class userApplications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userApplications()
        {
            this.customerAccounts = new HashSet<customerAccounts>();
            this.notificationLogs = new HashSet<notificationLogs>();
        }
    
        public int applicationId { get; set; }
        public string applicationNumber { get; set; }
        public string fullName { get; set; }
        public string mothersMaidenName { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string typeOfId { get; set; }
        public Nullable<int> idNumber { get; set; }
        public string gender { get; set; }
        public string civilStatus { get; set; }
        public string citizenship { get; set; }
        public string homeOwnership { get; set; }
        public string homeAddress { get; set; }
        public string employmentStatus { get; set; }
        public Nullable<int> totalHouseholdIncome { get; set; }
        public string occupation { get; set; }
        public string occupationRank { get; set; }
        public string businessName { get; set; }
        public string businessAddress { get; set; }
        public string officeTelephone { get; set; }
        public string status { get; set; }
        public string denialReason { get; set; }
        public string email { get; set; }
        public string plans { get; set; }
        public string modeOfPayment { get; set; }
        public string image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customerAccounts> customerAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notificationLogs> notificationLogs { get; set; }
    }
}
